"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_17iv77dt-3o2a6=&!rxdj8t9a%hb(3ngj=8w*cs-g)miz5f)6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",        # 사이트 도메인 관리
    
    # apps
    "movie",
    "app",
    
    # django rest framework and jwt
    "rest_framework",               # REST API 기능
    "rest_framework_simplejwt",     # JWT 발급 및 검증
    "rest_framework.authtoken",     # DRF 기본 토큰 인증
    "dj_rest_auth",                 # 로그인·로그아웃 API
    "dj_rest_auth.registration",    # 회원가입 API
    "allauth",                      # 계정 인증 기반
    "allauth.account",              # 일반 계정 관리
    "allauth.socialaccount",        # 소셜 로그인
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",     # allauth 계정 인증 요청 처리
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_AUTH = {
    "USE_JWT": True,                           # JWT 인증 사용
    "JWT_AUTH_HTTPONLY": True,                 # JavaScript의 쿠키 접근 차단
    "JWT_AUTH_COOKIE": "access_token",         # Access Token 쿠키 이름
    "JWT_AUTH_REFRESH_COOKIE": "refresh_token",# Refresh Token 쿠키 이름

    "JWT_AUTH_SECURE": False,                  # 로컬 HTTP에서도 쿠키 전송
    "JWT_AUTH_SAMESITE": "Lax",                # 외부 사이트 요청의 쿠키 전송 제한

    "JWT_AUTH_COOKIE_USE_CSRF": False,         # Postman 실습에서는 CSRF 검사 생략
    "SESSION_LOGIN": False,                    # Django 세션 로그인 사용 안 함
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # JWT 쿠키 인증을 기본으로 사용
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        # 기본적으로 인증된 사용자만 접근 허용
        "rest_framework.permissions.IsAuthenticated",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2), # 로그인 상태 유지 시간
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14), # 재발급 가능한 기간
    "ROTATE_REFRESH_TOKENS": False,
}

SITE_ID = 1    # 현재 사이트 ID 

ACCOUNT_EMAIL_VERIFICATION = "none"          # 이메일 인증 생략
ACCOUNT_LOGIN_METHODS = {"username"}  # username으로 로그인
