# Generated by Django 6.0.7 on 2026-08-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
