name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 가져오기
      - uses: actions/checkout@v4

      # 2. 파이썬 설치
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. 의존성 설치
      - run: pip install -r requirements.txt

      # 4. 테스트 실행
      - run: pytest
